apiVersion: v1
kind: Service
metadata:
  name: interceptor-service
  namespace: keda
spec:
  ports:
    - name: http-port-8080
      port: 8080
      targetPort: 8080
  selector:
    app: interceptor
