apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: keda
  name: scaler-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaler-rolebinding
  namespace: keda
subjects:
  - kind: ServiceAccount
    name: scaler
    namespace: keda
roleRef:
  kind: Role
  name: scaler-role
  apiGroup: rbac.authorization.k8s.io
